<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"  />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq"  />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketFlow.Contracts\TicketFlow.Contracts.csproj" />

    <ProjectReference Include="..\TicketFlow.Users.Domain\TicketFlow.Users.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Users.Application\TicketFlow.Users.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Users.Infrastructure\TicketFlow.Users.Infrastructure.csproj" />

    <ProjectReference Include="..\TicketFlow.Events.Domain\TicketFlow.Events.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Application\TicketFlow.Events.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Infrastructure\TicketFlow.Events.Infrastructure.csproj" />

    <ProjectReference Include="..\TicketFlow.Bookings.Domain\TicketFlow.Bookings.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Bookings.Application\TicketFlow.Bookings.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Bookings.Infrastructure\TicketFlow.Bookings.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>