<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketFlow.Contracts\TicketFlow.Contracts.csproj" />

    <ProjectReference Include="..\TicketFlow.Users.Domain\TicketFlow.Users.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Users.Application\TicketFlow.Users.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Users.Infrastructure\TicketFlow.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketFlow.Users.Presentation\TicketFlow.Users.Presentation.csproj" />

    <ProjectReference Include="..\TicketFlow.Events.Domain\TicketFlow.Events.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Application\TicketFlow.Events.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Infrastructure\TicketFlow.Events.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketFlow.Events.Presentation\TicketFlow.Events.Presentation.csproj" />

    <ProjectReference Include="..\TicketFlow.Bookings.Domain\TicketFlow.Bookings.Domain.csproj" />
    <ProjectReference Include="..\TicketFlow.Bookings.Application\TicketFlow.Bookings.Application.csproj" />
    <ProjectReference Include="..\TicketFlow.Bookings.Infrastructure\TicketFlow.Bookings.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketFlow.Bookings.Presentation\TicketFlow.Bookings.Presentation.csproj" />
  </ItemGroup>

</Project>